heat_template_version: '2018-08-31'

description: Simple heat template to deploy a single compute instance

resources:
  my_instance:
    type: OS::Nova::Server
    properties:
      key_name: default-key
      image: "CentOS 7.5.1804 (x86_64) [2018-06-06]"
      flavor: v2-highcpu-2
      networks:
        - network: public
